services:
  go-search:
    restart: always
    tty: true
    container_name: go-search
    hostname: go-search
    build:
      target: dev
      context: ../
      dockerfile: deployments/app/Dockerfile
    volumes:
      - ../:/src
    ports:
      - "8097:8097"
    env_file:
      - .env
    networks:
      - go-search-network
  go-search-postgres:
    image: postgres:17.2-alpine
    container_name: go-search-postgres
    restart: always
    volumes:
      - go-search-postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    ports:
      - 15434:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      SCHEMA: ${DB_SCHEMA}
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD}
    command: ["postgres", "-c", "wal_level=logical"]
    networks:
      - go-search-network
    
  go-search-redis:
    image: redis:8.4-alpine
    container_name: go-search-redis
    restart: always
    ports:
      - "63795:6379"
    volumes:
      - redis-data:/data
    networks:
      - go-search-network

  go-search-redis-insight:
    image: redis/redisinsight:latest
    container_name: go-search-redis-insight
    restart: always
    ports:
      - "5545:5540"
    volumes:
      - redis-insight-data:/data
    environment:
      - RI_REDIS_HOST_LOCAL=go-search-redis
      - RI_REDIS_PORT_LOCAL=6379
      - RI_ACCEPT_TERMS_AND_CONDITIONS=true
    depends_on:
      - go-search-redis
    networks:
      - go-search-network
  
  go-search-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: go-search-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - go-search-network

  go-search-postgres-test:
    image: postgres:17.2-alpine
    container_name: go-search-postgres-test
    restart: always
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    ports:
      - 15435:5432
    environment:
      POSTGRES_DB: ${DB_NAME}-test
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      SCHEMA: ${DB_SCHEMA}
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD}
    command: ["postgres", "-c", "wal_level=logical"]
    networks:
      - go-search-network
  
  go-search-elasticsearch-test:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: go-search-elasticsearch-test
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9201:9200"
    networks:
      - go-search-network

volumes:
  go-search-postgres-data:
    driver: local
  redis-data:
  redis-insight-data:
  es_data:

networks:
  go-search-network:
    name: go-search-network