version: '3.9'
services:
  go-search:
    restart: always
    tty: true
    container_name: go-search
    hostname: go-search
    build:
      target: dev
      context: ../
      dockerfile: deployments/app/Dockerfile
    volumes:
      - ../:/src
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - go-search-network
  go-search-postgres:
    image: postgres:17.2-alpine
    container_name: go-search-postgres
    restart: always
    volumes:
      - go-search-postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    ports:
      - 15434:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      SCHEMA: ${DB_SCHEMA}
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD}
    command: ["postgres", "-c", "wal_level=logical"]
    networks:
      - go-search-network

volumes:
  go-search-postgres-data:
    driver: local

networks:
  go-search-network:
    name: go-search-network