// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"go_search/pkg/httpclient"

	mock "github.com/stretchr/testify/mock"
)

// NewMockHTTPClient creates a new instance of MockHTTPClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHTTPClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHTTPClient {
	mock := &MockHTTPClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHTTPClient is an autogenerated mock type for the HTTPClient type
type MockHTTPClient struct {
	mock.Mock
}

type MockHTTPClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHTTPClient) EXPECT() *MockHTTPClient_Expecter {
	return &MockHTTPClient_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockHTTPClient
func (_mock *MockHTTPClient) Get(ctx context.Context, path string, headers httpclient.Headers, out any) error {
	ret := _mock.Called(ctx, path, headers, out)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, httpclient.Headers, any) error); ok {
		r0 = returnFunc(ctx, path, headers, out)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHTTPClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockHTTPClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
//   - headers httpclient.Headers
//   - out any
func (_e *MockHTTPClient_Expecter) Get(ctx interface{}, path interface{}, headers interface{}, out interface{}) *MockHTTPClient_Get_Call {
	return &MockHTTPClient_Get_Call{Call: _e.mock.On("Get", ctx, path, headers, out)}
}

func (_c *MockHTTPClient_Get_Call) Run(run func(ctx context.Context, path string, headers httpclient.Headers, out any)) *MockHTTPClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 httpclient.Headers
		if args[2] != nil {
			arg2 = args[2].(httpclient.Headers)
		}
		var arg3 any
		if args[3] != nil {
			arg3 = args[3].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockHTTPClient_Get_Call) Return(err error) *MockHTTPClient_Get_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHTTPClient_Get_Call) RunAndReturn(run func(ctx context.Context, path string, headers httpclient.Headers, out any) error) *MockHTTPClient_Get_Call {
	_c.Call.Return(run)
	return _c
}
