// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/machinebox/graphql"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGQLClient creates a new instance of MockGQLClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGQLClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGQLClient {
	mock := &MockGQLClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGQLClient is an autogenerated mock type for the GQLClient type
type MockGQLClient struct {
	mock.Mock
}

type MockGQLClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGQLClient) EXPECT() *MockGQLClient_Expecter {
	return &MockGQLClient_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockGQLClient
func (_mock *MockGQLClient) Run(ctx context.Context, req *graphql.Request, resp interface{}) error {
	ret := _mock.Called(ctx, req, resp)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *graphql.Request, interface{}) error); ok {
		r0 = returnFunc(ctx, req, resp)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGQLClient_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockGQLClient_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - req *graphql.Request
//   - resp interface{}
func (_e *MockGQLClient_Expecter) Run(ctx interface{}, req interface{}, resp interface{}) *MockGQLClient_Run_Call {
	return &MockGQLClient_Run_Call{Call: _e.mock.On("Run", ctx, req, resp)}
}

func (_c *MockGQLClient_Run_Call) Run(run func(ctx context.Context, req *graphql.Request, resp interface{})) *MockGQLClient_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *graphql.Request
		if args[1] != nil {
			arg1 = args[1].(*graphql.Request)
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGQLClient_Run_Call) Return(err error) *MockGQLClient_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGQLClient_Run_Call) RunAndReturn(run func(ctx context.Context, req *graphql.Request, resp interface{}) error) *MockGQLClient_Run_Call {
	_c.Call.Return(run)
	return _c
}
