// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"go_search/internal/article"

	mock "github.com/stretchr/testify/mock"
)

// NewMockBatchWriter creates a new instance of MockBatchWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBatchWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBatchWriter {
	mock := &MockBatchWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBatchWriter is an autogenerated mock type for the BatchWriter type
type MockBatchWriter struct {
	mock.Mock
}

type MockBatchWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBatchWriter) EXPECT() *MockBatchWriter_Expecter {
	return &MockBatchWriter_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockBatchWriter
func (_mock *MockBatchWriter) Run(ctx context.Context, articlesChan <-chan *article.Article, errChan chan<- error, runId string) {
	_mock.Called(ctx, articlesChan, errChan, runId)
	return
}

// MockBatchWriter_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockBatchWriter_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - articlesChan <-chan *article.Article
//   - errChan chan<- error
//   - runId string
func (_e *MockBatchWriter_Expecter) Run(ctx interface{}, articlesChan interface{}, errChan interface{}, runId interface{}) *MockBatchWriter_Run_Call {
	return &MockBatchWriter_Run_Call{Call: _e.mock.On("Run", ctx, articlesChan, errChan, runId)}
}

func (_c *MockBatchWriter_Run_Call) Run(run func(ctx context.Context, articlesChan <-chan *article.Article, errChan chan<- error, runId string)) *MockBatchWriter_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 <-chan *article.Article
		if args[1] != nil {
			arg1 = args[1].(<-chan *article.Article)
		}
		var arg2 chan<- error
		if args[2] != nil {
			arg2 = args[2].(chan<- error)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBatchWriter_Run_Call) Return() *MockBatchWriter_Run_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBatchWriter_Run_Call) RunAndReturn(run func(ctx context.Context, articlesChan <-chan *article.Article, errChan chan<- error, runId string)) *MockBatchWriter_Run_Call {
	_c.Run(run)
	return _c
}
