// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockBatchWriterMetrics creates a new instance of MockBatchWriterMetrics. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBatchWriterMetrics(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBatchWriterMetrics {
	mock := &MockBatchWriterMetrics{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBatchWriterMetrics is an autogenerated mock type for the BatchWriterMetrics type
type MockBatchWriterMetrics struct {
	mock.Mock
}

type MockBatchWriterMetrics_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBatchWriterMetrics) EXPECT() *MockBatchWriterMetrics_Expecter {
	return &MockBatchWriterMetrics_Expecter{mock: &_m.Mock}
}

// IncrementRunArticlesTotal provides a mock function for the type MockBatchWriterMetrics
func (_mock *MockBatchWriterMetrics) IncrementRunArticlesTotal(provider string, category string, runId string) {
	_mock.Called(provider, category, runId)
	return
}

// MockBatchWriterMetrics_IncrementRunArticlesTotal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementRunArticlesTotal'
type MockBatchWriterMetrics_IncrementRunArticlesTotal_Call struct {
	*mock.Call
}

// IncrementRunArticlesTotal is a helper method to define mock.On call
//   - provider string
//   - category string
//   - runId string
func (_e *MockBatchWriterMetrics_Expecter) IncrementRunArticlesTotal(provider interface{}, category interface{}, runId interface{}) *MockBatchWriterMetrics_IncrementRunArticlesTotal_Call {
	return &MockBatchWriterMetrics_IncrementRunArticlesTotal_Call{Call: _e.mock.On("IncrementRunArticlesTotal", provider, category, runId)}
}

func (_c *MockBatchWriterMetrics_IncrementRunArticlesTotal_Call) Run(run func(provider string, category string, runId string)) *MockBatchWriterMetrics_IncrementRunArticlesTotal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBatchWriterMetrics_IncrementRunArticlesTotal_Call) Return() *MockBatchWriterMetrics_IncrementRunArticlesTotal_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBatchWriterMetrics_IncrementRunArticlesTotal_Call) RunAndReturn(run func(provider string, category string, runId string)) *MockBatchWriterMetrics_IncrementRunArticlesTotal_Call {
	_c.Run(run)
	return _c
}
