// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockFetcherStorage creates a new instance of MockFetcherStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFetcherStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFetcherStorage {
	mock := &MockFetcherStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFetcherStorage is an autogenerated mock type for the FetcherStorage type
type MockFetcherStorage struct {
	mock.Mock
}

type MockFetcherStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFetcherStorage) EXPECT() *MockFetcherStorage_Expecter {
	return &MockFetcherStorage_Expecter{mock: &_m.Mock}
}

// GetLastFetchTime provides a mock function for the type MockFetcherStorage
func (_mock *MockFetcherStorage) GetLastFetchTime(ctx context.Context) (time.Time, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLastFetchTime")
	}

	var r0 time.Time
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (time.Time, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) time.Time); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFetcherStorage_GetLastFetchTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLastFetchTime'
type MockFetcherStorage_GetLastFetchTime_Call struct {
	*mock.Call
}

// GetLastFetchTime is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockFetcherStorage_Expecter) GetLastFetchTime(ctx interface{}) *MockFetcherStorage_GetLastFetchTime_Call {
	return &MockFetcherStorage_GetLastFetchTime_Call{Call: _e.mock.On("GetLastFetchTime", ctx)}
}

func (_c *MockFetcherStorage_GetLastFetchTime_Call) Run(run func(ctx context.Context)) *MockFetcherStorage_GetLastFetchTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFetcherStorage_GetLastFetchTime_Call) Return(time1 time.Time, err error) *MockFetcherStorage_GetLastFetchTime_Call {
	_c.Call.Return(time1, err)
	return _c
}

func (_c *MockFetcherStorage_GetLastFetchTime_Call) RunAndReturn(run func(ctx context.Context) (time.Time, error)) *MockFetcherStorage_GetLastFetchTime_Call {
	_c.Call.Return(run)
	return _c
}

// SetLastFetchTime provides a mock function for the type MockFetcherStorage
func (_mock *MockFetcherStorage) SetLastFetchTime(ctx context.Context, fetchTime time.Time) error {
	ret := _mock.Called(ctx, fetchTime)

	if len(ret) == 0 {
		panic("no return value specified for SetLastFetchTime")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) error); ok {
		r0 = returnFunc(ctx, fetchTime)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFetcherStorage_SetLastFetchTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLastFetchTime'
type MockFetcherStorage_SetLastFetchTime_Call struct {
	*mock.Call
}

// SetLastFetchTime is a helper method to define mock.On call
//   - ctx context.Context
//   - fetchTime time.Time
func (_e *MockFetcherStorage_Expecter) SetLastFetchTime(ctx interface{}, fetchTime interface{}) *MockFetcherStorage_SetLastFetchTime_Call {
	return &MockFetcherStorage_SetLastFetchTime_Call{Call: _e.mock.On("SetLastFetchTime", ctx, fetchTime)}
}

func (_c *MockFetcherStorage_SetLastFetchTime_Call) Run(run func(ctx context.Context, fetchTime time.Time)) *MockFetcherStorage_SetLastFetchTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFetcherStorage_SetLastFetchTime_Call) Return(err error) *MockFetcherStorage_SetLastFetchTime_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFetcherStorage_SetLastFetchTime_Call) RunAndReturn(run func(ctx context.Context, fetchTime time.Time) error) *MockFetcherStorage_SetLastFetchTime_Call {
	_c.Call.Return(run)
	return _c
}
