// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockFetcherMetrics creates a new instance of MockFetcherMetrics. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFetcherMetrics(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFetcherMetrics {
	mock := &MockFetcherMetrics{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFetcherMetrics is an autogenerated mock type for the FetcherMetrics type
type MockFetcherMetrics struct {
	mock.Mock
}

type MockFetcherMetrics_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFetcherMetrics) EXPECT() *MockFetcherMetrics_Expecter {
	return &MockFetcherMetrics_Expecter{mock: &_m.Mock}
}

// IncrementErrorsTotal provides a mock function for the type MockFetcherMetrics
func (_mock *MockFetcherMetrics) IncrementErrorsTotal(provider string, runID string) {
	_mock.Called(provider, runID)
	return
}

// MockFetcherMetrics_IncrementErrorsTotal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementErrorsTotal'
type MockFetcherMetrics_IncrementErrorsTotal_Call struct {
	*mock.Call
}

// IncrementErrorsTotal is a helper method to define mock.On call
//   - provider string
//   - runID string
func (_e *MockFetcherMetrics_Expecter) IncrementErrorsTotal(provider interface{}, runID interface{}) *MockFetcherMetrics_IncrementErrorsTotal_Call {
	return &MockFetcherMetrics_IncrementErrorsTotal_Call{Call: _e.mock.On("IncrementErrorsTotal", provider, runID)}
}

func (_c *MockFetcherMetrics_IncrementErrorsTotal_Call) Run(run func(provider string, runID string)) *MockFetcherMetrics_IncrementErrorsTotal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFetcherMetrics_IncrementErrorsTotal_Call) Return() *MockFetcherMetrics_IncrementErrorsTotal_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFetcherMetrics_IncrementErrorsTotal_Call) RunAndReturn(run func(provider string, runID string)) *MockFetcherMetrics_IncrementErrorsTotal_Call {
	_c.Run(run)
	return _c
}

// ObserveRunDuration provides a mock function for the type MockFetcherMetrics
func (_mock *MockFetcherMetrics) ObserveRunDuration(duration time.Duration, runID string) {
	_mock.Called(duration, runID)
	return
}

// MockFetcherMetrics_ObserveRunDuration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ObserveRunDuration'
type MockFetcherMetrics_ObserveRunDuration_Call struct {
	*mock.Call
}

// ObserveRunDuration is a helper method to define mock.On call
//   - duration time.Duration
//   - runID string
func (_e *MockFetcherMetrics_Expecter) ObserveRunDuration(duration interface{}, runID interface{}) *MockFetcherMetrics_ObserveRunDuration_Call {
	return &MockFetcherMetrics_ObserveRunDuration_Call{Call: _e.mock.On("ObserveRunDuration", duration, runID)}
}

func (_c *MockFetcherMetrics_ObserveRunDuration_Call) Run(run func(duration time.Duration, runID string)) *MockFetcherMetrics_ObserveRunDuration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Duration
		if args[0] != nil {
			arg0 = args[0].(time.Duration)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFetcherMetrics_ObserveRunDuration_Call) Return() *MockFetcherMetrics_ObserveRunDuration_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFetcherMetrics_ObserveRunDuration_Call) RunAndReturn(run func(duration time.Duration, runID string)) *MockFetcherMetrics_ObserveRunDuration_Call {
	_c.Run(run)
	return _c
}

// Push provides a mock function for the type MockFetcherMetrics
func (_mock *MockFetcherMetrics) Push() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Push")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFetcherMetrics_Push_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Push'
type MockFetcherMetrics_Push_Call struct {
	*mock.Call
}

// Push is a helper method to define mock.On call
func (_e *MockFetcherMetrics_Expecter) Push() *MockFetcherMetrics_Push_Call {
	return &MockFetcherMetrics_Push_Call{Call: _e.mock.On("Push")}
}

func (_c *MockFetcherMetrics_Push_Call) Run(run func()) *MockFetcherMetrics_Push_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFetcherMetrics_Push_Call) Return(err error) *MockFetcherMetrics_Push_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFetcherMetrics_Push_Call) RunAndReturn(run func() error) *MockFetcherMetrics_Push_Call {
	_c.Call.Return(run)
	return _c
}
