// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"go_search/internal/article"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockProviderRunner creates a new instance of MockProviderRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProviderRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProviderRunner {
	mock := &MockProviderRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProviderRunner is an autogenerated mock type for the ProviderRunner type
type MockProviderRunner struct {
	mock.Mock
}

type MockProviderRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProviderRunner) EXPECT() *MockProviderRunner_Expecter {
	return &MockProviderRunner_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockProviderRunner
func (_mock *MockProviderRunner) Run(ctx context.Context, articlesFrom time.Time) error {
	ret := _mock.Called(ctx, articlesFrom)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) error); ok {
		r0 = returnFunc(ctx, articlesFrom)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProviderRunner_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockProviderRunner_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - articlesFrom time.Time
func (_e *MockProviderRunner_Expecter) Run(ctx interface{}, articlesFrom interface{}) *MockProviderRunner_Run_Call {
	return &MockProviderRunner_Run_Call{Call: _e.mock.On("Run", ctx, articlesFrom)}
}

func (_c *MockProviderRunner_Run_Call) Run(run func(ctx context.Context, articlesFrom time.Time)) *MockProviderRunner_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProviderRunner_Run_Call) Return(err error) *MockProviderRunner_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProviderRunner_Run_Call) RunAndReturn(run func(ctx context.Context, articlesFrom time.Time) error) *MockProviderRunner_Run_Call {
	_c.Call.Return(run)
	return _c
}

// RunConcurrently provides a mock function for the type MockProviderRunner
func (_mock *MockProviderRunner) RunConcurrently(ctx context.Context, articlesFrom time.Time, articlesChan chan<- *article.Article, errChan chan<- error) {
	_mock.Called(ctx, articlesFrom, articlesChan, errChan)
	return
}

// MockProviderRunner_RunConcurrently_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunConcurrently'
type MockProviderRunner_RunConcurrently_Call struct {
	*mock.Call
}

// RunConcurrently is a helper method to define mock.On call
//   - ctx context.Context
//   - articlesFrom time.Time
//   - articlesChan chan<- *article.Article
//   - errChan chan<- error
func (_e *MockProviderRunner_Expecter) RunConcurrently(ctx interface{}, articlesFrom interface{}, articlesChan interface{}, errChan interface{}) *MockProviderRunner_RunConcurrently_Call {
	return &MockProviderRunner_RunConcurrently_Call{Call: _e.mock.On("RunConcurrently", ctx, articlesFrom, articlesChan, errChan)}
}

func (_c *MockProviderRunner_RunConcurrently_Call) Run(run func(ctx context.Context, articlesFrom time.Time, articlesChan chan<- *article.Article, errChan chan<- error)) *MockProviderRunner_RunConcurrently_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 chan<- *article.Article
		if args[2] != nil {
			arg2 = args[2].(chan<- *article.Article)
		}
		var arg3 chan<- error
		if args[3] != nil {
			arg3 = args[3].(chan<- error)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockProviderRunner_RunConcurrently_Call) Return() *MockProviderRunner_RunConcurrently_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockProviderRunner_RunConcurrently_Call) RunAndReturn(run func(ctx context.Context, articlesFrom time.Time, articlesChan chan<- *article.Article, errChan chan<- error)) *MockProviderRunner_RunConcurrently_Call {
	_c.Run(run)
	return _c
}
