// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"go_search/pkg/wiki"

	mock "github.com/stretchr/testify/mock"
)

// NewMockWikiClient creates a new instance of MockWikiClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWikiClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWikiClient {
	mock := &MockWikiClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWikiClient is an autogenerated mock type for the WikiClient type
type MockWikiClient struct {
	mock.Mock
}

type MockWikiClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWikiClient) EXPECT() *MockWikiClient_Expecter {
	return &MockWikiClient_Expecter{mock: &_m.Mock}
}

// GetArticleContent provides a mock function for the type MockWikiClient
func (_mock *MockWikiClient) GetArticleContent(ctx context.Context, request *wiki.GetArticleContentRequest) (*wiki.ArticleResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetArticleContent")
	}

	var r0 *wiki.ArticleResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *wiki.GetArticleContentRequest) (*wiki.ArticleResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *wiki.GetArticleContentRequest) *wiki.ArticleResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*wiki.ArticleResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *wiki.GetArticleContentRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWikiClient_GetArticleContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetArticleContent'
type MockWikiClient_GetArticleContent_Call struct {
	*mock.Call
}

// GetArticleContent is a helper method to define mock.On call
//   - ctx context.Context
//   - request *wiki.GetArticleContentRequest
func (_e *MockWikiClient_Expecter) GetArticleContent(ctx interface{}, request interface{}) *MockWikiClient_GetArticleContent_Call {
	return &MockWikiClient_GetArticleContent_Call{Call: _e.mock.On("GetArticleContent", ctx, request)}
}

func (_c *MockWikiClient_GetArticleContent_Call) Run(run func(ctx context.Context, request *wiki.GetArticleContentRequest)) *MockWikiClient_GetArticleContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *wiki.GetArticleContentRequest
		if args[1] != nil {
			arg1 = args[1].(*wiki.GetArticleContentRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWikiClient_GetArticleContent_Call) Return(articleResponse *wiki.ArticleResponse, err error) *MockWikiClient_GetArticleContent_Call {
	_c.Call.Return(articleResponse, err)
	return _c
}

func (_c *MockWikiClient_GetArticleContent_Call) RunAndReturn(run func(ctx context.Context, request *wiki.GetArticleContentRequest) (*wiki.ArticleResponse, error)) *MockWikiClient_GetArticleContent_Call {
	_c.Call.Return(run)
	return _c
}

// GetCategoryMembers provides a mock function for the type MockWikiClient
func (_mock *MockWikiClient) GetCategoryMembers(ctx context.Context, request *wiki.GetCategoryMembersRequest) (*wiki.CategoryMembersResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetCategoryMembers")
	}

	var r0 *wiki.CategoryMembersResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *wiki.GetCategoryMembersRequest) (*wiki.CategoryMembersResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *wiki.GetCategoryMembersRequest) *wiki.CategoryMembersResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*wiki.CategoryMembersResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *wiki.GetCategoryMembersRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWikiClient_GetCategoryMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCategoryMembers'
type MockWikiClient_GetCategoryMembers_Call struct {
	*mock.Call
}

// GetCategoryMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - request *wiki.GetCategoryMembersRequest
func (_e *MockWikiClient_Expecter) GetCategoryMembers(ctx interface{}, request interface{}) *MockWikiClient_GetCategoryMembers_Call {
	return &MockWikiClient_GetCategoryMembers_Call{Call: _e.mock.On("GetCategoryMembers", ctx, request)}
}

func (_c *MockWikiClient_GetCategoryMembers_Call) Run(run func(ctx context.Context, request *wiki.GetCategoryMembersRequest)) *MockWikiClient_GetCategoryMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *wiki.GetCategoryMembersRequest
		if args[1] != nil {
			arg1 = args[1].(*wiki.GetCategoryMembersRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWikiClient_GetCategoryMembers_Call) Return(categoryMembersResponse *wiki.CategoryMembersResponse, err error) *MockWikiClient_GetCategoryMembers_Call {
	_c.Call.Return(categoryMembersResponse, err)
	return _c
}

func (_c *MockWikiClient_GetCategoryMembers_Call) RunAndReturn(run func(ctx context.Context, request *wiki.GetCategoryMembersRequest) (*wiki.CategoryMembersResponse, error)) *MockWikiClient_GetCategoryMembers_Call {
	_c.Call.Return(run)
	return _c
}
