// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"go_search/pkg/devto"

	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// GetArticleById provides a mock function for the type MockClient
func (_mock *MockClient) GetArticleById(ctx context.Context, request *devto.GetArticlesByIdRequest) (*devto.Article, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetArticleById")
	}

	var r0 *devto.Article
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *devto.GetArticlesByIdRequest) (*devto.Article, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *devto.GetArticlesByIdRequest) *devto.Article); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*devto.Article)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *devto.GetArticlesByIdRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetArticleById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetArticleById'
type MockClient_GetArticleById_Call struct {
	*mock.Call
}

// GetArticleById is a helper method to define mock.On call
//   - ctx context.Context
//   - request *devto.GetArticlesByIdRequest
func (_e *MockClient_Expecter) GetArticleById(ctx interface{}, request interface{}) *MockClient_GetArticleById_Call {
	return &MockClient_GetArticleById_Call{Call: _e.mock.On("GetArticleById", ctx, request)}
}

func (_c *MockClient_GetArticleById_Call) Run(run func(ctx context.Context, request *devto.GetArticlesByIdRequest)) *MockClient_GetArticleById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *devto.GetArticlesByIdRequest
		if args[1] != nil {
			arg1 = args[1].(*devto.GetArticlesByIdRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_GetArticleById_Call) Return(article *devto.Article, err error) *MockClient_GetArticleById_Call {
	_c.Call.Return(article, err)
	return _c
}

func (_c *MockClient_GetArticleById_Call) RunAndReturn(run func(ctx context.Context, request *devto.GetArticlesByIdRequest) (*devto.Article, error)) *MockClient_GetArticleById_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestArticles provides a mock function for the type MockClient
func (_mock *MockClient) GetLatestArticles(ctx context.Context, request *devto.GetLatestArticlesRequest) ([]devto.ArticleSummary, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestArticles")
	}

	var r0 []devto.ArticleSummary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *devto.GetLatestArticlesRequest) ([]devto.ArticleSummary, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *devto.GetLatestArticlesRequest) []devto.ArticleSummary); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]devto.ArticleSummary)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *devto.GetLatestArticlesRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetLatestArticles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestArticles'
type MockClient_GetLatestArticles_Call struct {
	*mock.Call
}

// GetLatestArticles is a helper method to define mock.On call
//   - ctx context.Context
//   - request *devto.GetLatestArticlesRequest
func (_e *MockClient_Expecter) GetLatestArticles(ctx interface{}, request interface{}) *MockClient_GetLatestArticles_Call {
	return &MockClient_GetLatestArticles_Call{Call: _e.mock.On("GetLatestArticles", ctx, request)}
}

func (_c *MockClient_GetLatestArticles_Call) Run(run func(ctx context.Context, request *devto.GetLatestArticlesRequest)) *MockClient_GetLatestArticles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *devto.GetLatestArticlesRequest
		if args[1] != nil {
			arg1 = args[1].(*devto.GetLatestArticlesRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_GetLatestArticles_Call) Return(articleSummarys []devto.ArticleSummary, err error) *MockClient_GetLatestArticles_Call {
	_c.Call.Return(articleSummarys, err)
	return _c
}

func (_c *MockClient_GetLatestArticles_Call) RunAndReturn(run func(ctx context.Context, request *devto.GetLatestArticlesRequest) ([]devto.ArticleSummary, error)) *MockClient_GetLatestArticles_Call {
	_c.Call.Return(run)
	return _c
}
