// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"go_search/internal/article"
	"go_search/internal/provider"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockDevToProvider creates a new instance of MockDevToProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDevToProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDevToProvider {
	mock := &MockDevToProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDevToProvider is an autogenerated mock type for the DevToProvider type
type MockDevToProvider struct {
	mock.Mock
}

type MockDevToProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDevToProvider) EXPECT() *MockDevToProvider_Expecter {
	return &MockDevToProvider_Expecter{mock: &_m.Mock}
}

// FetchArticles provides a mock function for the type MockDevToProvider
func (_mock *MockDevToProvider) FetchArticles(ctx context.Context, articlesSince time.Time, query provider.Query) error {
	ret := _mock.Called(ctx, articlesSince, query)

	if len(ret) == 0 {
		panic("no return value specified for FetchArticles")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, provider.Query) error); ok {
		r0 = returnFunc(ctx, articlesSince, query)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDevToProvider_FetchArticles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchArticles'
type MockDevToProvider_FetchArticles_Call struct {
	*mock.Call
}

// FetchArticles is a helper method to define mock.On call
//   - ctx context.Context
//   - articlesSince time.Time
//   - query provider.Query
func (_e *MockDevToProvider_Expecter) FetchArticles(ctx interface{}, articlesSince interface{}, query interface{}) *MockDevToProvider_FetchArticles_Call {
	return &MockDevToProvider_FetchArticles_Call{Call: _e.mock.On("FetchArticles", ctx, articlesSince, query)}
}

func (_c *MockDevToProvider_FetchArticles_Call) Run(run func(ctx context.Context, articlesSince time.Time, query provider.Query)) *MockDevToProvider_FetchArticles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 provider.Query
		if args[2] != nil {
			arg2 = args[2].(provider.Query)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDevToProvider_FetchArticles_Call) Return(err error) *MockDevToProvider_FetchArticles_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDevToProvider_FetchArticles_Call) RunAndReturn(run func(ctx context.Context, articlesSince time.Time, query provider.Query) error) *MockDevToProvider_FetchArticles_Call {
	_c.Call.Return(run)
	return _c
}

// FetchArticlesAsync provides a mock function for the type MockDevToProvider
func (_mock *MockDevToProvider) FetchArticlesAsync(ctx context.Context, articlesSince time.Time, query provider.Query, articlesChan chan<- *article.Article) error {
	ret := _mock.Called(ctx, articlesSince, query, articlesChan)

	if len(ret) == 0 {
		panic("no return value specified for FetchArticlesAsync")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, provider.Query, chan<- *article.Article) error); ok {
		r0 = returnFunc(ctx, articlesSince, query, articlesChan)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDevToProvider_FetchArticlesAsync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchArticlesAsync'
type MockDevToProvider_FetchArticlesAsync_Call struct {
	*mock.Call
}

// FetchArticlesAsync is a helper method to define mock.On call
//   - ctx context.Context
//   - articlesSince time.Time
//   - query provider.Query
//   - articlesChan chan<- *article.Article
func (_e *MockDevToProvider_Expecter) FetchArticlesAsync(ctx interface{}, articlesSince interface{}, query interface{}, articlesChan interface{}) *MockDevToProvider_FetchArticlesAsync_Call {
	return &MockDevToProvider_FetchArticlesAsync_Call{Call: _e.mock.On("FetchArticlesAsync", ctx, articlesSince, query, articlesChan)}
}

func (_c *MockDevToProvider_FetchArticlesAsync_Call) Run(run func(ctx context.Context, articlesSince time.Time, query provider.Query, articlesChan chan<- *article.Article)) *MockDevToProvider_FetchArticlesAsync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 provider.Query
		if args[2] != nil {
			arg2 = args[2].(provider.Query)
		}
		var arg3 chan<- *article.Article
		if args[3] != nil {
			arg3 = args[3].(chan<- *article.Article)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockDevToProvider_FetchArticlesAsync_Call) Return(err error) *MockDevToProvider_FetchArticlesAsync_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDevToProvider_FetchArticlesAsync_Call) RunAndReturn(run func(ctx context.Context, articlesSince time.Time, query provider.Query, articlesChan chan<- *article.Article) error) *MockDevToProvider_FetchArticlesAsync_Call {
	_c.Call.Return(run)
	return _c
}
