// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"go_search/internal/article"

	mock "github.com/stretchr/testify/mock"
)

// NewMockArticleRepository creates a new instance of MockArticleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockArticleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockArticleRepository {
	mock := &MockArticleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockArticleRepository is an autogenerated mock type for the ArticleRepository type
type MockArticleRepository struct {
	mock.Mock
}

type MockArticleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockArticleRepository) EXPECT() *MockArticleRepository_Expecter {
	return &MockArticleRepository_Expecter{mock: &_m.Mock}
}

// UpsertArticle provides a mock function for the type MockArticleRepository
func (_mock *MockArticleRepository) UpsertArticle(ctx context.Context, article1 *article.Article) error {
	ret := _mock.Called(ctx, article1)

	if len(ret) == 0 {
		panic("no return value specified for UpsertArticle")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *article.Article) error); ok {
		r0 = returnFunc(ctx, article1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockArticleRepository_UpsertArticle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertArticle'
type MockArticleRepository_UpsertArticle_Call struct {
	*mock.Call
}

// UpsertArticle is a helper method to define mock.On call
//   - ctx context.Context
//   - article1 *article.Article
func (_e *MockArticleRepository_Expecter) UpsertArticle(ctx interface{}, article1 interface{}) *MockArticleRepository_UpsertArticle_Call {
	return &MockArticleRepository_UpsertArticle_Call{Call: _e.mock.On("UpsertArticle", ctx, article1)}
}

func (_c *MockArticleRepository_UpsertArticle_Call) Run(run func(ctx context.Context, article1 *article.Article)) *MockArticleRepository_UpsertArticle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *article.Article
		if args[1] != nil {
			arg1 = args[1].(*article.Article)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockArticleRepository_UpsertArticle_Call) Return(err error) *MockArticleRepository_UpsertArticle_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockArticleRepository_UpsertArticle_Call) RunAndReturn(run func(ctx context.Context, article1 *article.Article) error) *MockArticleRepository_UpsertArticle_Call {
	_c.Call.Return(run)
	return _c
}
