// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"go_search/pkg/hashnode"

	mock "github.com/stretchr/testify/mock"
)

// NewMockHashnodeClient creates a new instance of MockHashnodeClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHashnodeClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHashnodeClient {
	mock := &MockHashnodeClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHashnodeClient is an autogenerated mock type for the HashnodeClient type
type MockHashnodeClient struct {
	mock.Mock
}

type MockHashnodeClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHashnodeClient) EXPECT() *MockHashnodeClient_Expecter {
	return &MockHashnodeClient_Expecter{mock: &_m.Mock}
}

// GetPostsByTag provides a mock function for the type MockHashnodeClient
func (_mock *MockHashnodeClient) GetPostsByTag(ctx context.Context, request *hashnode.PostsByTagRequest) (*hashnode.PostsByTagResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetPostsByTag")
	}

	var r0 *hashnode.PostsByTagResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *hashnode.PostsByTagRequest) (*hashnode.PostsByTagResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *hashnode.PostsByTagRequest) *hashnode.PostsByTagResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*hashnode.PostsByTagResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *hashnode.PostsByTagRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHashnodeClient_GetPostsByTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPostsByTag'
type MockHashnodeClient_GetPostsByTag_Call struct {
	*mock.Call
}

// GetPostsByTag is a helper method to define mock.On call
//   - ctx context.Context
//   - request *hashnode.PostsByTagRequest
func (_e *MockHashnodeClient_Expecter) GetPostsByTag(ctx interface{}, request interface{}) *MockHashnodeClient_GetPostsByTag_Call {
	return &MockHashnodeClient_GetPostsByTag_Call{Call: _e.mock.On("GetPostsByTag", ctx, request)}
}

func (_c *MockHashnodeClient_GetPostsByTag_Call) Run(run func(ctx context.Context, request *hashnode.PostsByTagRequest)) *MockHashnodeClient_GetPostsByTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *hashnode.PostsByTagRequest
		if args[1] != nil {
			arg1 = args[1].(*hashnode.PostsByTagRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHashnodeClient_GetPostsByTag_Call) Return(postsByTagResponse *hashnode.PostsByTagResponse, err error) *MockHashnodeClient_GetPostsByTag_Call {
	_c.Call.Return(postsByTagResponse, err)
	return _c
}

func (_c *MockHashnodeClient_GetPostsByTag_Call) RunAndReturn(run func(ctx context.Context, request *hashnode.PostsByTagRequest) (*hashnode.PostsByTagResponse, error)) *MockHashnodeClient_GetPostsByTag_Call {
	_c.Call.Return(run)
	return _c
}
